/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GlennPhillipBaluyot
 */
public final class ViewSalaryGUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewSalaryGUI
     */
    public ViewSalaryGUI() {
        initComponents();
    }
    
    private int employeeID;
    
    public ViewSalaryGUI(int employeeID)
    {
        initComponents();
        this.employeeID = employeeID;      

    }
    
    private void loadSalaryInformation(int employeeID) {
        // Here you would fetch the employee data (basicSalary and allowance) based on the employeeID
        EmployeeDatabase db = new EmployeeDatabase("employees.csv", "credentials.csv");
        User employee = db.getEmployeeByID(employeeID);

        if (employee != null) {
            double basicSalary = employee.getBasicSalary();
            double allowance = employee.getAllowance();

            // Calculate the Gross Salary and Net Salary
            double grossSalary = PayrollCalculator.calculateGrossSalary(basicSalary, allowance);
            double netSalary = PayrollCalculator.calculateNetSalary(grossSalary, allowance);

            // Display the results in the label
            jLabelSalary.setText("<html>Payslip for " + jComboBoxMonth.getSelectedItem() + " " + jComboBoxYear.getSelectedItem()  + "<br>Gross Salary: " + grossSalary + "<br>Net Salary: " + netSalary + "</html>");
        } else {
            jLabelSalary.setText("Employee not found.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSalaryInformation = new javax.swing.JPanel();
        jLabelSalary = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jLabelPrintPayslip = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jButtonPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSalaryInformation.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSalaryInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payroll Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        javax.swing.GroupLayout jPanelSalaryInformationLayout = new javax.swing.GroupLayout(jPanelSalaryInformation);
        jPanelSalaryInformation.setLayout(jPanelSalaryInformationLayout);
        jPanelSalaryInformationLayout.setHorizontalGroup(
            jPanelSalaryInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaryInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalary)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanelSalaryInformationLayout.setVerticalGroup(
            jPanelSalaryInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalaryInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSalary)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June ", "July", "August", "September", "October", "November", "December" }));
        jComboBoxMonth.setToolTipText("Month");

        jLabelPrintPayslip.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPrintPayslip.setText("Print Payslip Information");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025" }));
        jComboBoxYear.setToolTipText("Month");

        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelPrintPayslip)
                    .addComponent(jPanelSalaryInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelPrintPayslip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPrint))
                .addGap(18, 18, 18)
                .addComponent(jPanelSalaryInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
        loadSalaryInformation(employeeID);
    }//GEN-LAST:event_jButtonPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSalaryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSalaryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabelPrintPayslip;
    private javax.swing.JLabel jLabelSalary;
    private javax.swing.JPanel jPanelSalaryInformation;
    // End of variables declaration//GEN-END:variables
}
